#!/usr/bin/env python3

import argparse
import sys
import os
import pkg_resources
sys.path.append('../')
sys.path.append('./')
from  saffrontree.SaffronTree import SaffronTree
from  saffrontree.InputTypes import InputTypes

version = ''
try:
	version = pkg_resources.get_distribution("saffrontree").version
except pkg_resources.DistributionNotFound:
	version = 'x.y.z'

parser = argparse.ArgumentParser(
	description = 'A tool to generate a tree from raw reads',
	usage = 'saffrontree [options] output_directory *.fastq.gz')
parser.add_argument('output_directory', help='Output directory', type=InputTypes.is_output_directory_valid )
parser.add_argument('fastq_files', help='FASTQ files which may be gzipped', nargs='+', type=InputTypes.is_fastqs_valid)
parser.add_argument('--kmer',	                     '-k', help='Kmer to use, depends on read length [%(default)s]', type=InputTypes.is_kmer_valid,  default = 31)
parser.add_argument('--min_kmers_threshold',	     '-m', help='Exclude k-mers occurring less than this [%(default)s]', type=InputTypes.is_min_kmers_threshold_valid,  default = 5)
parser.add_argument('--max_kmers_threshold',	     '-x', help='Exclude k-mers occurring more than this [%(default)s]', type=InputTypes.is_max_kmers_threshold_valid,  default = 255)
parser.add_argument('--threads',                     '-t', help='Number of threads [%(default)s]', type=InputTypes.is_threads_valid,  default = 1)
parser.add_argument('--verbose',                     '-v', action='count', help='Turn on debugging [%(default)s]', default = 0)
parser.add_argument('--version', action='version', version=str(version))

options = parser.parse_args()

saffron_tree = SaffronTree(options)
saffron_tree.run()
